server:
    port: 8761 #指定服务器端口
spring:
    application:
        name: spring-cloud-eureka
    security:   #securety用户认证
        basic:
         enabled: true #开启基于Http basic认证
        user:
         name:   admin   #配置登录的账号是user
         password:   admin   #配置登录的密码是password123
eureka:
    client:
        registerWithEureka: false #是否将自己注册到Eureka Server默认为true由于当前应用就是Eureka Server 故而设为false
        fetchRegistry: false        #表示是否从Eureka Server获取注册信息，默认为true，因为这是单节点的Eureka Server，不需要同步其他的Eureka Server节点的数据故设置为false
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8761/eureka/ #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka/多个地址可使用,分割
